apiVersion: v2
appVersion: "1.0"
description: A Helm chart for Log and Audit Frontend App
name: lau-frontend
home: https://github.com/hmcts/lau-frontend
version: 0.0.64
dependencies:
  - name: nodejs
    version: 3.0.2
    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/'
  - name: redis
    version: 18.6.3
    repository: 'https://charts.bitnami.com/bitnami'
    condition: redis.enabled
