nodejs:
  applicationPort: 4000
  aadIdentityName: lau
  ingressHost: lau.{{ .Values.global.environment }}.platform.hmcts.net
  image: 'hmctspublic.azurecr.io/lau/frontend:latest'
  environment:
    USE_REDIS: true
    REDIS_USE_TLS: true
    REDIS_PORT: 6380
    REDIS_HOST: lau-frontend-session-storage-{{ .Values.global.environment }}.redis.cache.windows.net
    LAU_CASE_BACKEND_URL: http://lau-case-backend-pr-45.service.core-compute-preview.internal
    LAU_IDAM_BACKEND_URL: http://lau-idam-backend-pr-45.service.core-compute-preview.internal
    IDAM_WEB_URL: https://idam-web-public.{{ .Values.global.environment }}.platform.hmcts.net/login
    IDAM_API_URL: https://idam-api.{{ .Values.global.environment }}.platform.hmcts.net/o/token
    S2S_URL: http://rpe-service-auth-provider-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    OAUTH_CLIENT_REDIRECT: https://lau.{{ .Values.global.environment }}.platform.hmcts.net/oauth2/callback
    ALLOW_CONFIG_MUTATIONS: true


  keyVaults:
    lau:
      resourceGroup: lau
      secrets:
        - AppInsightsInstrumentationKey
        - frontend-redis-access-key
        - idam-client-secret
        - s2s-secret

redis:
  cluster:
    enabled: false
    slaveCount: 0
  usePassword: false
  master:
    persistence:
      enabled: false
  enabled: false

idam-pr:
  enabled: false
