nodejs:
  applicationPort: 4000
  aadIdentityName: lau
  ingressHost: lau.{{ .Values.global.environment }}.platform.hmcts.net
  image: 'hmctspublic.azurecr.io/lau/frontend:latest'
  spotInstances:
    enabled: false
  environment:
    REFORM_TEAM: lau
    REFORM_SERVICE_NAME: lau-frontend
    REFORM_ENVIRONMENT: '{{ .Values.global.environment }}'
    USE_REDIS: true
    REDIS_USE_TLS: true
    REDIS_PORT: 6380
    REDIS_HOST: lau-frontend-session-storage-{{ .Values.global.environment }}.redis.cache.windows.net
    LAU_CASE_BACKEND_URL: http://lau-case-backend-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    LAU_IDAM_BACKEND_URL: http://lau-idam-backend-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    LAU_EUD_BACKEND_URL: http://lau-eud-backend-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    IDAM_WEB_URL: https://idam-web-public.{{ .Values.global.environment }}.platform.hmcts.net/login
    IDAM_API_URL: https://idam-api.{{ .Values.global.environment }}.platform.hmcts.net
    S2S_URL: http://rpe-service-auth-provider-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    OAUTH_CLIENT_REDIRECT: https://lau.{{ .Values.global.environment }}.platform.hmcts.net/oauth2/callback
    ALLOW_CONFIG_MUTATIONS: true
    DUMMY_RESTART_VAR: 1
    IS_DEV: true
    OTEL_SERVICE_NAME: lau-frontend
    USER_DETAILS_PAGE_ENABLED: true

  keyVaults:
    lau:
      resourceGroup: lau
      secrets:
        - app-insights-connection-string
        - frontend-redis-access-key
        - idam-client-secret
        - s2s-secret
        - launchdarkly-sdk-key
        - lau-deleted-users-ft

redis:
  architecture: standalone
  auth:
    enabled: false
  usePassword: false
  master:
    persistence:
      enabled: false
  enabled: false

idam-pr:
  enabled: false
