nodejs:
  # Don't modify below here
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  environment:
    OAUTH_CLIENT_REDIRECT: https://${SERVICE_FQDN}/oauth2/callback
    OTEL_SDK_DISABLED:  true
    

redis:
  enabled: true
